create schema master;

create table complex (
    _id text,
    category  text not null,
    name text not null,
    developer_name text,
    address_street text,
    address_city text,
    address_subdistrict text,
    address_urban text,
    address_province text,
    address_zip text,
    address_coordinate text,
    create_by_uid text,
    facilities json,
    images json,
    id text,
    tower_total int,
    branches json,
    unit_rent_total double precision,
    unit_sell_total double precision,
    developer_legal_name text,
    land_size double precision,
    last_update_at timestamp,
    last_update_by_uid text,
    address_country text,
    surrounding_area json,
    address_area json,
    create_at timestamp,
    status double precision,
    code text,
    service_types json,
    premium_listing_available text,
    IsActive boolean not null,
    insert_date timestamp default current_timestamp
);


create table tower (
    _id text,
    complex_id  text,
    create_by_id text,
    last_update_at timestamp,
    category text not null,
    name text not null,
    year_completion int,
    year_renovation int,
    floor_count int,
    description json,
    parking json,
    lift json,
    internet json,
    images json,
    unit_total int,
    id text,
    branches json,
    unit_rent_total double precision,
    unit_sell_total double precision,
    architect text,
    certificate text,
    contractor text,
    fee_component json,
    last_update_by_uid text,
    promo text,
    rent_commission double precision,
    sell_commission double precision,
    year_completed_estimation int,
    year_construction int,
    building_type json,
    service_charge double precision,
    auto_description boolean,
    is_leads_agent boolean,
    average_floor_plate double precision,
    ceiling_height double precision,
    commercial_terms double precision,
    condition text,
    electricity double precision,
    fire_safety double precision,
    grade text,
    land_size double precision,
    max_zone_per_floor double precision,
    office_hours double precision,
    power_line double precision,
    selling_point json,
    semi_gross_area double precision,
    sinking_fund double precision,
    complex json,
    create_at timestamp,
    status double precision,
    include_scsf text,
    total_unit_primary double precision,
    isactive boolean not null,
    insert_date timestamp default current_timestamp
);


create table master.complex
(
    _id text not null
        constraint complex_pkey
            primary key,
    category text not null,
    name text not null,
    developer_name text,
    address_street text,
    address_city text,
    address_subdistrict text,
    address_urban text,
    address_province text,
    address_zip text,
    address_coordinate text,
    create_by_uid text,
    facilities json,
    images json,
    tower_total integer,
    branches json,
    unit_rent_total double precision,
    unit_sell_total double precision,
    developer_legal_name text,
    land_size double precision,
    last_update_at timestamp,
    last_update_by_uid text,
    address_country text,
    surrounding_area json,
    address_area json,
    create_at timestamp,
    status double precision,
    code text,
    service_types json,
    premium_listing_available text,
    isactive boolean not null,
    create_timestamp timestamp default CURRENT_TIMESTAMP,
    update_timestamp timestamp default CURRENT_TIMESTAMP
);


create table master.tower
(
    _id text not null
        constraint tower_pkey
            primary key,
    name text,
    category text,
    complex_id text,
    year_completion integer,
    year_completed_estimation integer,
    year_construction integer,
    year_renovation integer,
    architect text,
    contractor text,
    certificate text,
    service_charge double precision,
    sinking_fund double precision,
    promo text,
    last_update_by_uid text,
    last_update_at timestamp,
    isactive boolean,
    create_timestamp timestamp default CURRENT_TIMESTAMP,
    update_timestamp timestamp default CURRENT_TIMESTAMP
);

create table master.unit
(
    _id text not null
        constraint unit_pkey
            primary key,
    complex_id text,
    category text,
    land_size double precision,
    unit_total integer,
    floor_count integer,
    max_zone_pe_floor double precision,
    unit_rent_total double precision,
    unit_sell_total double precision,
    rent_commission double precision,
    sell_commission double precision,
    parking json,
    lift json,
    building_type json,
    internet json,
    total_unit_primary double precision,
    isactive boolean,
    create_timestamp timestamp default CURRENT_TIMESTAMP,
    update_timestamp timestamp default CURRENT_TIMESTAMP
);


create table master.analytic_property (
       complex_id text,
       tower_id text,
       category text,
       complex_name text,
       name_of_tower text,
       land_size double precision,
       street text,
       zip_code text,
       subdistrict text,
       urban text,
       city text,
       province text,
       country text,
       developer_name text,
       unit_total int,
       floor_count int,
       tower_year_completion int,
       tower_service_charge double precision,
       promo text,
       unit_rent_total double precision,
       unit_sell_total double precision,
       rent_commission double precision,
       sell_commission double precision,
       service_types text,
       facilities text,
       car_parking text,
       motor_parking text,
       total_lift_passenger int,
       total_lift_service int,
       internet text,
       building_type text,
       last_update_complex timestamp,
       last_update_tower_unit timestamp,
       is_active_complex boolean,
       is_active_tower boolean,
       create_timestamp timestamp default  current_timestamp,
       update_timestamp timestamp default current_timestamp
);